import React, { Component } from 'react'


const Advisors = () => (
    
    <div className='advisors'>
        <h2>OUR ADVISORS</h2>
        <p>
            ADVIROSSSSSSSSSSSSSSSSSSSSSSSSSSSADVIROSSSSSSSSSSSSSSSSSSSSSSSSSSSADVIROSSSSSSSSSSSSSSSSSSSSSSSSSSS
            ADVIROSSSSSSSSSSSSSSSSSSSSSSSSSSSADVIROSSSSSSSSSSSSSSSSSSSSSSSSSSSADVIROSSSSSSSSSSSSSSSSSSSSSSSSSSS
            ADVIROSSSSSSSSSSSSSSSSSSSSSSSSSSSADVIROSSSSSSSSSSSSSSSSSSSSSSSSSSSADVIROSSSSSSSSSSSSSSSSSSSSSSSSSSS
            ADVIROSSSSSSSSSSSSSSSSSSSSSSSSSSSADVIROSSSSSSSSSSSSSSSSSSSSSSSSSSSADVIROSSSSSSSSSSSSSSSSSSSSSSSSSSS
            ADVIROSSSSSSSSSSSSSSSSSSSSSSSSSSSADVIROSSSSSSSSSSSSSSSSSSSSSSSSSSSADVIROSSSSSSSSSSSSSSSSSSSSSSSSSSS
            ADVIROSSSSSSSSSSSSSSSSSSSSSSSSSSSADVIROSSSSSSSSSSSSSSSSSSSSSSSSSSSADVIROSSSSSSSSSSSSSSSSSSSSSSSSSSS
            ADVIROSSSSSSSSSSSSSSSSSSSSSSSSSSS
            ADVIROSSSSSSSSSSSSSSSSSSSSSSSSSSS
            ADVIROSSSSSSSSSSSSSSSSSSSSSSSSSSS
            ADVIROSSSSSSSSSSSSSSSSSSSSSSSSSSS 
        </p>
    </div>

)

export default Advisors